import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "./globals.css";
import "../app/styles/globals.css";

import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "@/app/components/layout/navbar/navbar";
import { ColorModeScript } from "@chakra-ui/react";
import theme from "../app/styles/theme";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ColorModeScript initialColorMode={theme.config.initialColorMode}/>
    <ChakraProvider>
      <Navbar/>
      {children}
    </ChakraProvider>
    </body>
    </html>
  );
}
